var1 = input("please enter an adjective: ")
var2 = input("please enter an adjective: ")
var3 = input("please enter a type of bird: ")
var4 = input("please enter a room in a house: ")
var5 = input("please enter a verb (past tense): ")
var6 = input("please enter a verb: ")
var7 = input("please enter a relative's name: ")
var8 = input("please enter a noun: ")
var9 = input("please enter a liquid: ")
var10 = input("please enter a verb ending in \"-ing\": ")
var11 = input("please enter a part of the body (plural): ")
var12 = input("please enter a plural noun: ")
var13 = input("please enter a verb ending in \"-ing\": ")
var14 = input("please enter a noun: ")

print()

print("It was a " + var1 + " cold November day.")
print("I woke up to the " + var2 + " smell of " + var3 + " roasting in the " + var4 + " downstairs.")
print("I " + var5 + " down the stairs to see if I could help " + var6 + " with the dinner.")
print("My mom said, 'See if " + var7 + " needs a fresh " + var8 + ".'")
print("So, I carried a tray of glasses full of " + var9 + " into the " + var10 + " room.")
print("When I got there, I couldn't believe my " + var11 + "; there were " + var12 + " " + var13 + " on the " + var14 + "!")